name: NPM Download Statistics

on:
  schedule:
    # Run every Sunday at 00:00 UTC
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  collect-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Collect npm statistics
        run: npm run collect-stats

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        permissions:
          contents: write
        run: |
          git add data/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update npm download statistics

            🤖 Automated weekly update of npm download statistics"
            git push
          fi